#!/bin/bash

# EXEMPLO PRÁTICO: Implementar campo "priority" opcional com padrão "normal"

echo "🎯 EXEMPLO: Implementando campo 'priority' opcional"
echo ""

# Exemplo de uso do script automatizado
echo "1. 📁 Vamos supor que queremos adicionar um campo 'priority' opcional"
echo "   no schema de mensagens com valor padrão 'normal'"
echo ""

echo "2. 🔧 Comando que usaríamos:"
echo "   ./scripts/make_field_optional.sh app/schemas/chat.py priority normal"
echo ""

echo "3. 📝 Resultado esperado no arquivo:"
echo ""
echo "   # ANTES:"
echo "   priority: str = Field(..., max_length=20)"
echo ""
echo "   # DEPOIS:"
echo "   priority: Optional[str] = Field(default=\"normal\", max_length=20)"
echo ""
echo "   @validator('priority', pre=True, always=True)"
echo "   def validate_priority(cls, v):"
echo "       if v is None or (isinstance(v, str) and not v.strip()):"
echo "           return \"normal\""
echo "       return v.strip().lower()"
echo ""

echo "4. 🧪 Teste que faríamos:"
echo ""
echo "   # Sem o campo priority (deve usar 'normal')"
echo "   curl -X POST 'http://localhost:8000/api/v1/messages' \\"
echo "   -H 'Content-Type: application/json' \\"
echo "   -d '{"
echo "     \"client_id\": \"123e4567-e89b-12d3-a456-426614174002\","
echo "     \"message\": \"Preciso de ajuda\""
echo "   }'"
echo ""

echo "5. 📊 Resultado esperado:"
echo "   {"
echo "     \"client_id\": \"123e4567-e89b-12d3-a456-426614174002\","
echo "     \"sector\": \"geral\","
echo "     \"priority\": \"normal\","
echo "     \"message\": \"Preciso de ajuda\","
echo "     \"id\": 19,"
echo "     ..."
echo "   }"
echo ""

echo "⏱️  Tempo total: ~30 segundos"
echo "🎉 Processo documentado e automatizado!"
echo ""
echo "📚 Para mais detalhes, consulte:"
echo "   - docs/PYDANTIC_OPTIONAL_FIELDS_GUIDE.md (guia completo)"
echo "   - docs/QUICK_REFERENCE.md (referência rápida)"
echo "   - scripts/make_field_optional.sh (automação)"
